//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCatLabTask.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int P_Id { get; set; }
        public string P_Name { get; set; }
        public int Price { get; set; }
        public int CatId { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
